# Generated by Django 4.2.13 on 2024-05-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemo_corpora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemogene',
            name='gene_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
